version: "3.9"

services:
  db:
    image: postgres:12-alpine
    container_name: authenticationapp_postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - authenticationappnetwork

  app:
    image: authenticationapp
    container_name: authenticationapp_fastapi
    ports:
      - 8000:8000
    volumes:
      - .:/home
    depends_on:
      - db
    networks:
      - authenticationappnetwork

networks:
  authenticationappnetwork: